import { describe, it, expect, vi, beforeEach } from 'vitest';
import { getEmbeddings } from './embedding-service.js';
import { getPipelineInstance } from '../config/pipeline.js';

vi.mock('../config/pipeline.js', () => ({
  getPipelineInstance: vi.fn(),
}));

describe('Embedding Service', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should return embeddings of the exact size and sequential order as the input texts', async () => {
    const mockTexts = ['first sentence', 'second sentence', 'third sentence'];
    
    // Mock the embeddings that would normally be generated by the Hugging Face transformer
    const mockEmbeddings = [
      [0.1, 0.2, 0.3], // corresponds to 'first sentence'
      [0.4, 0.5, 0.6], // corresponds to 'second sentence'
      [0.7, 0.8, 0.9], // corresponds to 'third sentence'
    ];

    // The pipeline instance is a function that returns an object with a tolist() method
    const mockPipelineFn = vi.fn().mockResolvedValue({
      tolist: () => mockEmbeddings,
    });

    vi.mocked(getPipelineInstance).mockResolvedValue(mockPipelineFn);

    const result = await getEmbeddings(mockTexts);

    // Verify pipeline initialization was called
    expect(getPipelineInstance).toHaveBeenCalledOnce();
    
    // Verify pipeline processing was called with our specific inputs and options
    expect(mockPipelineFn).toHaveBeenCalledWith(mockTexts, {
      pooling: 'mean',
      normalize: true,
    });

    // Test that the batch sizes match (the length of input equals length of output)
    expect(result.length).toBe(mockTexts.length);
    
    // Test sequential correspondence: the returned embeddings match our mocked order sequentially
    expect(result).toEqual(mockEmbeddings);
    expect(result[0]).toEqual(mockEmbeddings[0]);
    expect(result[1]).toEqual(mockEmbeddings[1]);
    expect(result[2]).toEqual(mockEmbeddings[2]);
  });

  it('should throw an error if the pipeline returns a different number of embeddings than texts provided', async () => {
    const mockTexts = ['first sentence', 'second sentence'];
    
    // Simulating a failure where only 1 embedding is returned for 2 input texts
    const mismatchedEmbeddings = [
      [0.1, 0.2, 0.3]
    ];

    const mockPipelineFn = vi.fn().mockResolvedValue({
      tolist: () => mismatchedEmbeddings,
    });

    vi.mocked(getPipelineInstance).mockResolvedValue(mockPipelineFn);

    await expect(getEmbeddings(mockTexts)).rejects.toThrow(
      'Embedding mismatch: Got 1 embeddings for 2 texts.'
    );
  });
});
